# Generated by Django 4.0.4 on 2022-06-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_photo_delete_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
