# Generated by Django 4.0.4 on 2022-06-01 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='name',
        ),
    ]
