# Generated by Django 4.0.4 on 2022-06-01 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_photo_delete_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='xray_image',
            new_name='inputfile',
        ),
    ]
